version: '3.8'

services:
  postgres:
    image: postgres:14.1
    container_name: demo-db
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "35432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Optionally, you can define the Spring Boot application service here
  # spring-boot-app:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/demo
  #     SPRING_DATASOURCE_USERNAME: postgres
  #     SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  postgres_data:
